# Generated by Django 5.0.6 on 2024-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_email_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="verification_code",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="verification_code_created_at",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
